super-agent:
  author: sgnxotsmicf
  version: 0.20
  description: 多智能体平台服务项目

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: SuperAgent
  ai:
    chat:
      observations:
        log-prompt: false  #提示词日志(包含系统提示词、框架提示词和用户输入的完整输入)
        log-completion: false  # 模型响应日志
        include-error-logging: true
      client:  # 客户端观测日志
        observations:
          log-prompt: false
          log-completion: false
    vectorstore:
      observations:
        log-query-response: false
    tools:
      observations:
        include-content: false
    alibaba:
      arms:
        enabled: true
        model:
          capture-input: true
          capture-output: true
        tool:
          enabled: true
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json


# 基础设施配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0   #全量链路追踪（1.0=全采样，0=关闭）

logging:
  level:
    org.springframework.ai.deepseek: info
    org.springframework.ai: info
    # 阿里云ARMS
    com.alibaba.arms: info
    # 关闭中间件冗余日志
    org.redisson: warn
    org.springframework.amqp: warn
    com.alibaba.druid: warn
    org.apache.tomcat: warn
    root: info


server:
  port: 8123
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.sgnxotsmicf
knife4j:
  enable: true
  setting:
    language: zh_cn


# mp
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
      logic-delete-field: deleted # 全局逻辑删除字段名(deleted为实体类属性名称)
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0
    banner: false
  mapper-locations: classpath*:/mapper/**/*.xml

ai:
  upload:
    max-size: 10485760  # 10MB
    allow-types: image/png,image/jpeg,image/jpg,image/webp,audio/mp3,audio/wav,video/mp4
